# Generated by Django 4.1.3 on 2022-11-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://i.etsystatic.com/5895745/r/il/8df936/359042918/il_75x75.359042918.jpg', max_length=510),
        ),
    ]
